# Generated by Django 2.0.9 on 2024-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_payment_alert',
            name='month',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='pay_payment_alert',
            name='year',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
